### PR TITLE
Setup components

### PR DESCRIPTION
**Pull request by Epaltechs**
### Here is what I have done in this first milestone of the project:
- Initialise React app.
- Create a directory for components.
- Add [React Router](https://reactrouter.com/web/guides/quick-start)
- Add the default view of Books.
- Create a component called Book for displaying a single book.
- Add a form for adding a book with inputs for a title and author.
- Add Categories to display a button "Check status" only.

### CODE REVIEW

**Review by julie-ify — CHANGES_REQUESTED** [review]
Hi @Epaltechs,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted a project with no linters and no descriptive README. You need to move the files in the highlighted `bookstore` folder to the root path so that your linters can run and your README will be reflected

  epal-readme

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Epaltechs** [comment]
Thanks, @julie-ify, that suggestion has saved me a whole lot of headache. I've tried severally to figure out why there were no linter errors in my local repository, but there were on Github. I appreciate you.

**Review by julie-ify — APPROVED** [review]
Hi @Epaltechs,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by julie-ify** [comment]
> Thanks, @julie-ify, that suggestion has saved me a whole lot of headache. I've tried severally to figure out why there were no linter errors in my local repository, but there were on Github. I appreciate you.

@Epaltechs You're welcome. Glad to have helped.

**Pull request merged**
